package com.base.app.baseapp.utils

import com.base.app.baseapp.model.FoodItem

object Constants {
    const val SHARE_PREFERENCE_NAME = "PREFERENCE_SAVE_DATA"

    val listItem = listOf(
        FoodItem(
            name = "Táo",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/Images/haiyen/2018/12/10/tao.jpg",
            category = "Trái cây",
            gi = 36,
            gl = 4.176f,
            carb = 14f,
            chatXo = 2.4f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "150–200g/ngày (1-2 quả)",
            khauPhanTienTieuDuong = "≤100g/ngày (~1 quả) + kèm protein",
            khauPhanTieuDuong1 = "1 quả (25g carb) + điều chỉnh insulin",
            khauPhanTieuDuong2 = "80g/ngày (½ quả)",
            khauPhanBienChungThan = "50g/ngày (¼ quả)",
            id = 3
        ),
        FoodItem(
            name = "Chuối",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2021/10/14/chuoi1-16341869574602070184903.jpg",
            category = "Trái cây",
            gi = 51,
            gl = 10.404f,
            carb = 23f,
            chatXo = 2.6f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 quả/ngày (120–240g)",
            khauPhanTienTieuDuong = "≤50g/ngày (~½ quả) + kèm bơ đậu phộng",
            khauPhanTieuDuong1 = "1/2 quả (12g carb)",
            khauPhanTieuDuong2 = "30g/ngày (¼ quả)",
            khauPhanBienChungThan = "Không khuyến khích (kali cao)",
            id = 4
        ),
        FoodItem(
            name = "Gạo lứt",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/Images/nguyenkhanh/2018/08/25/nhung-tac-dung-cua-gao-luc-doi-voi-suc-khoe.-1.jpg",
            category = "Ngũ cốc",
            gi = 68,
            gl = 14.416f,
            carb = 23f,
            chatXo = 1.8f,
            typeGI = 2,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "1 chén/bữa + rau xanh",
            khauPhanTieuDuong1 = "1 chén (45g carb)",
            khauPhanTieuDuong2 = "1/2 chén/bữa",
            khauPhanBienChungThan = "50g/bữa",
            id = 9
        ),
        FoodItem(
            name = "Gạo trắng",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/8/16/chon-gao-ngon-16606367955691866664148.jpg",
            category = "Ngũ cốc",
            gi = 73,
            gl = 20.148f,
            carb = 28f,
            chatXo = 0.4f,
            typeGI = 3,
            typeGL = 3,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "≤1/2 chén/bữa",
            khauPhanTieuDuong1 = "1/2 chén (30g carb)",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh",
            id = 63
        ),
        FoodItem(
            name = "Khoai tây",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/12/10/chuyencuakhoaitaytb1-16706853682851812514449.jpg",
            category = "Rau củ",
            gi = 82,
            gl = 14.596f,
            carb = 20f,
            chatXo = 2.2f,
            typeGI = 3,
            typeGL = 2,
            khauPhanKhongBenh = "100–150g/bữa",
            khauPhanTienTieuDuong = "≤50g/bữa (½ củ nhỏ) + luộc cả vỏ",
            khauPhanTieuDuong1 = "50g (10g carb)",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh (kali cao)",
            id = 41
        ),
        FoodItem(
            name = "Khoai lang",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2021/10/3/khoai-lang-16332714337561040798892.jpg",
            category = "Rau củ",
            gi = 54,
            gl = 11.340f,
            carb = 24f,
            chatXo = 3f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "100–200g/bữa (1–2 củ)",
            khauPhanTienTieuDuong = "80g/bữa (1 củ nhỏ) + hấp nguyên củ",
            khauPhanTieuDuong1 = "100g (24g carb)",
            khauPhanTieuDuong2 = "50g/bữa (½ củ)",
            khauPhanBienChungThan = "30g/bữa (¼ củ)",
            id = 57
        ),
        FoodItem(
            name = "Bánh mì trắng",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/2015/1-31433421873thucpham1434517009208981d0effb9cp-1434599209506.jpg",
            category = "Ngũ cốc",
            gi = 75,
            gl = 34.725f,
            carb = 49f,
            chatXo = 2.7f,
            typeGI = 3,
            typeGL = 3,
            khauPhanKhongBenh = "1–2 lát/bữa",
            khauPhanTienTieuDuong = "Tránh",
            khauPhanTieuDuong1 = "1 lát (15g carb)",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh",
            id = 62
        ),
        FoodItem(
            name = "Bánh mì nguyên cám",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/10/9/banh-mi-nguyen-cam-16968314742341417739489.png",
            category = "Ngũ cốc",
            gi = 50,
            gl = 17.500f,
            carb = 41f,
            chatXo = 6f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "2–3 lát/bữa",
            khauPhanTienTieuDuong = "1 lát/bữa + phô mai",
            khauPhanTieuDuong1 = "1 lát (20g carb)",
            khauPhanTieuDuong2 = "1 lát/bữa",
            khauPhanBienChungThan = "1 lát/bữa (nếu kali thấp)",
            id = 65
        ),
        FoodItem(
            name = "Yến mạch",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/11/7/ava-an-yen-mach-co-tot-khong-1667813110424720981416-18-0-393-600-crop-16678131198401393927978.jpg",
            category = "Ngũ cốc",
            gi = 55,
            gl = 30.745f,
            carb = 66f,
            chatXo = 10.1f,
            typeGI = 1,
            typeGL = 3,
            khauPhanKhongBenh = "40–50g/bữa",
            khauPhanTienTieuDuong = "30g/bữa + sữa hạnh nhân",
            khauPhanTieuDuong1 = "30g (20g carb)",
            khauPhanTieuDuong2 = "20g/bữa",
            khauPhanBienChungThan = "20g/bữa (nếu kali thấp)",
            id = 34
        ),
        FoodItem(
            name = "Nho",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2025/3/7/nho-den-va-nho-xanh-17413424268951013270137.png",
            category = "Trái cây",
            gi = 43,
            gl = 6.923f,
            carb = 17f,
            chatXo = 0.9f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "100–150g/ngày (20–30 trái)",
            khauPhanTienTieuDuong = "≤50g/ngày (~10 trái) + kèm hạt",
            khauPhanTieuDuong1 = "50g (~10 trái)",
            khauPhanTieuDuong2 = "30g/ngày (~6 trái)",
            khauPhanBienChungThan = "Tránh (kali cao)",
            id = 25
        ),
        FoodItem(
            name = "Dưa hấu",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/720_450/Images/thuhuong/2021/07/04/bo-sung-chat-chong-o-xy-hoa-tu-dua-hau1625376265.jpg",
            category = "Trái cây",
            gi = 72,
            gl = 5.472f,
            carb = 8f,
            chatXo = 0.4f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "200–300g/ngày (2–3 miếng)",
            khauPhanTienTieuDuong = "≤100g/ngày (1 miếng)",
            khauPhanTieuDuong1 = "100g (1 miếng)",
            khauPhanTieuDuong2 = "50g/ngày (½ miếng)",
            khauPhanBienChungThan = "Tránh (kali thấp nhưng GI cao)",
            id = 60
        ),
        FoodItem(
            name = "Dâu tây",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/2015/4-loi-ich-tuyet-voi-cua-dau-tay-4-1422241944000.jpg",
            category = "Trái cây",
            gi = 40,
            gl = 2.000f,
            carb = 7f,
            chatXo = 2f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "150–200g/ngày (15–20 trái)",
            khauPhanTienTieuDuong = "100g/ngày (~10 trái)",
            khauPhanTieuDuong1 = "100g (10 trái)",
            khauPhanTieuDuong2 = "100g/ngày (10 trái)",
            khauPhanBienChungThan = "100g/ngày (10 trái)",
            id = 54
        ),
        FoodItem(
            name = "Sữa nguyên kem",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2024/7/23/sua-1721707681690797870370.jpg",
            category = "Sữa",
            gi = 31,
            gl = 1.550f,
            carb = 5f,
            chatXo = 0f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "200–300ml/ngày",
            khauPhanTienTieuDuong = "150ml/ngày",
            khauPhanTieuDuong1 = "200ml (5g carb)",
            khauPhanTieuDuong2 = "150ml/ngày",
            khauPhanBienChungThan = "100ml/ngày (nếu không biến chứng)",
            id = 64
        ),
        FoodItem(
            name = "Sữa tách béo",
            imageUrl = "https://giadinh.mediacdn.vn/k:thumb_w/640/2015/anh-1-1447125464216/uong-sua-tach-beo-co-the-giam-kha-nang-sinh-san.jpg",
            category = "Sữa",
            gi = 32,
            gl = 1.440f,
            carb = 4.5f,
            chatXo = 0f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "200–300ml/ngày",
            khauPhanTienTieuDuong = "150ml/ngày",
            khauPhanTieuDuong1 = "200ml (4.5g carb)",
            khauPhanTieuDuong2 = "150ml/ngày",
            khauPhanBienChungThan = "100ml/ngày",
            id = 50
        ),
        FoodItem(
            name = "Sữa chua không đường",
            imageUrl = "https://icdn.dantri.com.vn/2018/5/17/sua-chua-15265083373392117657059.jpg",
            category = "Sữa",
            gi = 14,
            gl = 0.840f,
            carb = 6f,
            chatXo = 0f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 hộp/ngày",
            khauPhanTienTieuDuong = "1 hộp/ngày",
            khauPhanTieuDuong1 = "1 hộp (6g carb)",
            khauPhanTieuDuong2 = "1 hộp/ngày",
            khauPhanBienChungThan = "1 hộp/ngày",
            id = 55
        ),
        FoodItem(
            name = "Cam",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/Images/thanhloan/2016/06/05/tac-dung-cua-qua-cam-2.jpg",
            category = "Trái cây",
            gi = 48,
            gl = 3.600f,
            carb = 9f,
            chatXo = 1.5f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 quả/ngày (130–260g)",
            khauPhanTienTieuDuong = "1 quả/ngày (130g)",
            khauPhanTieuDuong1 = "1 quả (9g carb)",
            khauPhanTieuDuong2 = "1/2 quả/ngày (65g)",
            khauPhanBienChungThan = "Tránh (kali cao)",
            id = 35
        ),
        FoodItem(
            name = "Lê",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/480_300/324455921873985536/2025/1/22/le-la-loai-trai-cay-bo-duong-1737542486320850768651-25-0-665-1024-crop-173754249478527470732.png",
            category = "Trái cây",
            gi = 38,
            gl = 3.002f,
            carb = 11f,
            chatXo = 3.1f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 quả/ngày (180–360g)",
            khauPhanTienTieuDuong = "1 quả/ngày (180g)",
            khauPhanTieuDuong1 = "1 quả (11g carb)",
            khauPhanTieuDuong2 = "1/2 quả/ngày (90g)",
            khauPhanBienChungThan = "1/2 quả/ngày (90g)",
            id = 37
        ),
        FoodItem(
            name = "Đậu lăng",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/600_315/Images/thutrang/2016/01/11/an-dau-lang-rat-co-loi-cho-suc-khoe1452496030.jpg",
            category = "Họ đậu",
            gi = 30,
            gl = 3.030f,
            carb = 18f,
            chatXo = 7.9f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "50–100g/ngày",
            khauPhanTienTieuDuong = "≤50g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "50g (15g carb)",
            khauPhanTieuDuong2 = "≤30g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 30
        ),
        FoodItem(
            name = "Đậu xanh",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/600_315/Images/duylinh/2018/04/17/dau-xanh-thuc-pham-vang-cho-suc-khoe1523954747.jpg",
            category = "Họ đậu",
            gi = 25,
            gl = 1.925f,
            carb = 16f,
            chatXo = 8.3f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "50–100g/ngày",
            khauPhanTienTieuDuong = "≤50g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "50g (15g carb)",
            khauPhanTieuDuong2 = "≤30g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 33
        ),
        FoodItem(
            name = "Hạnh nhân",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/Images/phamhiep/2018/11/26/hanh-nhan-tri-hen-phe-quan1455964156.jpg",
            category = "Hạt",
            gi = 10,
            gl = -0.600f,
            carb = 6f,
            chatXo = 12f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "15–30g/ngày",
            khauPhanTienTieuDuong = "≤15g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "10g (5g carb)",
            khauPhanTieuDuong2 = "≤10g/ngày",
            khauPhanBienChungThan = "Tránh nếu phospho cao",
            id = 1
        ),
        FoodItem(
            name = "Khoai sọ",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/10/9/photo-1696837615296-1696837615829424200322.jpg",
            category = "Rau củ",
            gi = 50,
            gl = 8.900f,
            carb = 21f,
            chatXo = 3.2f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "100–150g/bữa",
            khauPhanTienTieuDuong = "≤50g/bữa + luộc cả vỏ",
            khauPhanTieuDuong1 = "50g (10g carb)",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh (kali cao)",
            id = 58
        ),
        FoodItem(
            name = "Mì ống lúa mì",
            imageUrl = "https://cdn.pixabay.com/photo/2020/02/24/15/05/penne-pasta-4876503_1280.jpg",
            category = "Ngũ cốc",
            gi = 45,
            gl = 16.290f,
            carb = 40f,
            chatXo = 3.8f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "1 chén/bữa + rau xanh",
            khauPhanTieuDuong1 = "1 chén (45g carb)",
            khauPhanTieuDuong2 = "1/2 chén/bữa",
            khauPhanBienChungThan = "50g/bữa",
            id = 61
        ),
        FoodItem(
            name = "Bột yến mạch",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2024/7/9/yen-mach-1-17205402143381302921554-0-0-640-1024-crop-1720540218878280477635.jpg",
            category = "Ngũ cốc",
            gi = 54,
            gl = 27.486f,
            carb = 55f,
            chatXo = 4.1f,
            typeGI = 1,
            typeGL = 3,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "1 chén/bữa + rau xanh",
            khauPhanTieuDuong1 = "1 chén (45g carb)",
            khauPhanTieuDuong2 = "1/2 chén/bữa",
            khauPhanBienChungThan = "50g/bữa",
            id = 34
        ),
        FoodItem(
            name = "Hạt chia",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/720_450/324455921873985536/2025/5/27/photo-1748357278785-1748357279182848275590-0-0-632-1011-crop-17483573818421525196061.jpeg",
            category = "Hạt",
            gi = 1,
            gl = 0.080f,
            carb = 42f,
            chatXo = 34f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "15–30g/ngày",
            khauPhanTienTieuDuong = "≤15g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "10g (5g carb)",
            khauPhanTieuDuong2 = "≤10g/ngày",
            khauPhanBienChungThan = "Tránh nếu phospho cao",
            id = 15
        ),
        FoodItem(
            name = "Hạt điều",
            imageUrl = "https://vfa.gov.vn//uploads/news/3656/7-ly-do-ban-nen-an-hat-dieu-ngay-tu-hom-nay.jpg",
            category = "Hạt",
            gi = 22,
            gl = 5.940f,
            carb = 30f,
            chatXo = 3f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "15–30g/ngày",
            khauPhanTienTieuDuong = "≤15g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "10g (5g carb)",
            khauPhanTieuDuong2 = "≤10g/ngày",
            khauPhanBienChungThan = "Tránh nếu phospho cao",
            id = 13
        ),
        FoodItem(
            name = "Bánh quy",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2024/8/5/photo-1722824756814-1722824757026234918665.jpeg",
            category = "Bánh ngọt",
            gi = 70,
            gl = 41.300f,
            carb = 60f,
            chatXo = 1f,
            typeGI = 3,
            typeGL = 3,
            khauPhanKhongBenh = "1–2 cái/bữa",
            khauPhanTienTieuDuong = "Tránh",
            khauPhanTieuDuong1 = "Tránh",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh",
            id = 18
        ),
        FoodItem(
            name = "Mật ong",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/480_300/Images/_OLD/2014/uongmat-ong-1397400609991.jpg",
            category = "Đồ ngọt",
            gi = 58,
            gl = 46.400f,
            carb = 80f,
            chatXo = 0f,
            typeGI = 2,
            typeGL = 3,
            khauPhanKhongBenh = "1–2 thìa cà phê/ngày",
            khauPhanTienTieuDuong = "Tránh",
            khauPhanTieuDuong1 = "Tránh",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh",
            id = 26
        ),
        FoodItem(
            name = "Nước ngọt có ga",
            imageUrl = "https://mediabls.mediatech.vn/upload/image/202305/thumbnail/48341_1-8.jpg",
            category = "Đồ uống",
            gi = 65,
            gl = 58.500f,
            carb = 90f,
            chatXo = 0f,
            typeGI = 2,
            typeGL = 3,
            khauPhanKhongBenh = "Tránh",
            khauPhanTienTieuDuong = "Tránh",
            khauPhanTieuDuong1 = "Tránh",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh",
            id = 11
        ),
        FoodItem(
            name = "Sô cô la đen",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/thumb_w/640/324455921873985536/2022/2/13/so-co-la-2-16447236273331251818477.jpg",
            category = "Đồ ngọt",
            gi = 23,
            gl = 9.890f,
            carb = 50f,
            chatXo = 7f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "20–30g/ngày",
            khauPhanTienTieuDuong = "10g/ngày",
            khauPhanTieuDuong1 = "15g (7.5g carb)",
            khauPhanTieuDuong2 = "10g/ngày",
            khauPhanBienChungThan = "Tránh (phốt pho cao)",
            id = 21
        ),
        FoodItem(
            name = "Xoài",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/1/16/images2790076anxoai1-1673888776151453324557.jpg",
            category = "Trái cây",
            gi = 76,
            gl = 14.516f,
            carb = 22.9f,
            chatXo = 3.8f,
            typeGI = 3,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 quả/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + kèm protein",
            khauPhanTieuDuong1 = "1 quả (25g carb) + điều chỉnh insulin",
            khauPhanTieuDuong2 = "80g/ngày",
            khauPhanBienChungThan = "Tránh nước ép",
            id = 32
        ),
        FoodItem(
            name = "Bơ",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/Images/nguyenkhanh/2019/05/10/qua_bo.jpg",
            category = "Trái cây",
            gi = 35,
            gl = 8.225f,
            carb = 27f,
            chatXo = 3.5f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 quả/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + kèm protein",
            khauPhanTieuDuong1 = "1 quả (25g carb) + điều chỉnh insulin",
            khauPhanTieuDuong2 = "80g/ngày",
            khauPhanBienChungThan = "Tránh nước ép",
            id = 0
        ),
        FoodItem(
            name = "Dứa",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2025/4/18/dua-8-17448826700541269965864-1744961954767-17449619552111279931847.jpg",
            category = "Trái cây",
            gi = 83,
            gl = 5.893f,
            carb = 15.6f,
            chatXo = 8.5f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 quả/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + kèm protein",
            khauPhanTieuDuong1 = "1 quả (25g carb) + điều chỉnh insulin",
            khauPhanTieuDuong2 = "80g/ngày",
            khauPhanBienChungThan = "Tránh nước ép",
            id = 38
        ),
        FoodItem(
            name = "Mít",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2024/6/26/mit-1719419474602825625781.jpg",
            category = "Trái cây",
            gi = 61,
            gl = 9.760f,
            carb = 17.9f,
            chatXo = 1.9f,
            typeGI = 2,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 quả/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + kèm protein",
            khauPhanTieuDuong1 = "1 quả (25g carb) + điều chỉnh insulin",
            khauPhanTieuDuong2 = "80g/ngày",
            khauPhanBienChungThan = "Tránh nước ép",
            id = 27
        ),
        FoodItem(
            name = "Mận",
            imageUrl = "https://www.baolongan.vn/image/news/2024/20240518/images/qua-man-17159981001721534359815.webp",
            category = "Trái cây",
            gi = 73,
            gl = 13.943f,
            carb = 26.6f,
            chatXo = 7.5f,
            typeGI = 3,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 quả/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + kèm protein",
            khauPhanTieuDuong1 = "1 quả (25g carb) + điều chỉnh insulin",
            khauPhanTieuDuong2 = "80g/ngày",
            khauPhanBienChungThan = "Tránh nước ép",
            id = 39
        ),
        FoodItem(
            name = "Ngô",
            imageUrl = "https://photo-baomoi.bmcdn.me/w500_r1/2024_05_07_91_49033375/840a3a70f03c1962402d.jpg",
            category = "Ngũ cốc",
            gi = 51,
            gl = 4.182f,
            carb = 18.2f,
            chatXo = 10f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "1 chén/bữa + rau xanh",
            khauPhanTieuDuong1 = "1 chén (45g carb)",
            khauPhanTieuDuong2 = "1/2 chén/bữa",
            khauPhanBienChungThan = "50g/bữa",
            id = 19
        ),
        FoodItem(
            name = "Lúa mạch",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/4/29/dai-thao-duong-co-nen-an-yen-mach2-1651228024254324399743.jpg",
            category = "Ngũ cốc",
            gi = 80,
            gl = 0.800f,
            carb = 7.9f,
            chatXo = 6.9f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "1 chén/bữa + rau xanh",
            khauPhanTieuDuong1 = "1 chén (45g carb)",
            khauPhanTieuDuong2 = "1/2 chén/bữa",
            khauPhanBienChungThan = "50g/bữa",
            id = 5
        ),
        FoodItem(
            name = "Bột mì",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/12/4/dai-thao-duong-nen-an-gi-0-17016737942251154411607.jpg",
            category = "Ngũ cốc",
            gi = 32,
            gl = 8.704f,
            carb = 30.3f,
            chatXo = 3.1f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "1 chén/bữa + rau xanh",
            khauPhanTieuDuong1 = "1 chén (45g carb)",
            khauPhanTieuDuong2 = "1/2 chén/bữa",
            khauPhanBienChungThan = "50g/bữa",
            id = 24
        ),
        FoodItem(
            name = "Bột gạo",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/Images/bichvan/2017/04/05/rice.jpg",
            category = "Ngũ cốc",
            gi = 78,
            gl = 4.758f,
            carb = 13.8f,
            chatXo = 7.7f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 chén/bữa",
            khauPhanTienTieuDuong = "1 chén/bữa + rau xanh",
            khauPhanTieuDuong1 = "1 chén (45g carb)",
            khauPhanTieuDuong2 = "1/2 chén/bữa",
            khauPhanBienChungThan = "50g/bữa",
            id = 45
        ),
        FoodItem(
            name = "Bí đỏ",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/Images/phamhiep/2019/12/10/bi-do-mon-an-bo-duong-vi-thuoc-quy1575961201.jpg",
            category = "Rau củ",
            gi = 77,
            gl = 24.024f,
            carb = 32.6f,
            chatXo = 1.4f,
            typeGI = 3,
            typeGL = 3,
            khauPhanKhongBenh = "100–150g/bữa",
            khauPhanTienTieuDuong = "≤50g/bữa + luộc cả vỏ",
            khauPhanTieuDuong1 = "50g (10g carb)",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh (kali cao)",
            id = 42
        ),
        FoodItem(
            name = "Cà rốt",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2025/1/13/photo-1736755538553-17367555393311498040186.png",
            category = "Rau củ",
            gi = 50,
            gl = 10.550f,
            carb = 29.8f,
            chatXo = 8.7f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "100–150g/bữa",
            khauPhanTienTieuDuong = "≤50g/bữa + luộc cả vỏ",
            khauPhanTieuDuong1 = "50g (10g carb)",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh (kali cao)",
            id = 12
        ),
        FoodItem(
            name = "Su hào",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2024/11/5/su-hao-1730777012641216161997.jpg",
            category = "Rau củ",
            gi = 51,
            gl = 11.424f,
            carb = 28.3f,
            chatXo = 5.9f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "100–150g/bữa",
            khauPhanTienTieuDuong = "≤50g/bữa + luộc cả vỏ",
            khauPhanTieuDuong1 = "50g (10g carb)",
            khauPhanTieuDuong2 = "Tránh",
            khauPhanBienChungThan = "Tránh (kali cao)",
            id = 28
        ),
        FoodItem(
            name = "Đậu đen",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/600_315/Images/hohuong/2021/04/29/dau-den-thuoc-quy-tri-nhieu-benh1619689338.jpg",
            category = "Họ đậu",
            gi = 79,
            gl = 8.216f,
            carb = 18.8f,
            chatXo = 8.4f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "50–100g/ngày",
            khauPhanTienTieuDuong = "≤50g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "50g (15g carb)",
            khauPhanTieuDuong2 = "≤30g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 8
        ),
        FoodItem(
            name = "Đậu đỏ",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/8/21/photo-1692635479175-169263547976456701626.jpg",
            category = "Họ đậu",
            gi = 53,
            gl = 7.526f,
            carb = 15.2f,
            chatXo = 1f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "50–100g/ngày",
            khauPhanTienTieuDuong = "≤50g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "50g (15g carb)",
            khauPhanTieuDuong2 = "≤30g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 44
        ),
        FoodItem(
            name = "Đậu nành",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/static/uploads/editor/dau-nanh-ban-luan.jpg",
            category = "Họ đậu",
            gi = 47,
            gl = 9.259f,
            carb = 21.8f,
            chatXo = 2.1f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "50–100g/ngày",
            khauPhanTienTieuDuong = "≤50g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "50g (15g carb)",
            khauPhanTieuDuong2 = "≤30g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 52
        ),
        FoodItem(
            name = "Hạt óc chó",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/zoom/720_450/324455921873985536/2025/2/4/organic-walnuts-in-shell-173863969186767907907-80-0-393-500-crop-17386397004291524898496.jpg",
            category = "Hạt",
            gi = 66,
            gl = 11.550f,
            carb = 20.8f,
            chatXo = 3.3f,
            typeGI = 2,
            typeGL = 2,
            khauPhanKhongBenh = "15–30g/ngày",
            khauPhanTienTieuDuong = "≤15g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "10g (5g carb)",
            khauPhanTieuDuong2 = "≤10g/ngày",
            khauPhanBienChungThan = "Tránh nếu phospho cao",
            id = 59
        ),
        FoodItem(
            name = "Hạt mè",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2023/9/26/cong-dung-tuyet-voi-cua-hat-vung-doi-voi-suc-khoe-169570229736928962296.jpeg",
            category = "Hạt",
            gi = 72,
            gl = 12.672f,
            carb = 19.2f,
            chatXo = 1.6f,
            typeGI = 3,
            typeGL = 2,
            khauPhanKhongBenh = "15–30g/ngày",
            khauPhanTienTieuDuong = "≤15g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "10g (5g carb)",
            khauPhanTieuDuong2 = "≤10g/ngày",
            khauPhanBienChungThan = "Tránh nếu phospho cao",
            id = 47
        ),
        FoodItem(
            name = "Hạt hướng dương",
            imageUrl = "https://cdn.tgdd.vn/2021/05/CookProduct/Tac-dung-cua-hat-huong-duong-doi-voi-suc-khoe-va-cach-an-hat-huong-duong-0-1200x676-1200x676-1.jpg",
            category = "Hạt",
            gi = 56,
            gl = 18.928f,
            carb = 36.4f,
            chatXo = 2.6f,
            typeGI = 2,
            typeGL = 2,
            khauPhanKhongBenh = "15–30g/ngày",
            khauPhanTienTieuDuong = "≤15g/ngày + kết hợp rau",
            khauPhanTieuDuong1 = "10g (5g carb)",
            khauPhanTieuDuong2 = "≤10g/ngày",
            khauPhanBienChungThan = "Tránh nếu phospho cao",
            id = 56
        ),
        FoodItem(
            name = "Sữa bò",
            imageUrl = "https://vuayenmach.vn/wp-content/uploads/2021/04/sb.jpg",
            category = "Sữa",
            gi = 66,
            gl = 11.814f,
            carb = 23f,
            chatXo = 5.1f,
            typeGI = 2,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 ly/ngày",
            khauPhanTienTieuDuong = "≤200ml/ngày + không đường",
            khauPhanTieuDuong1 = "1 ly (12g carb)",
            khauPhanTieuDuong2 = "≤1 ly/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và phospho cao",
            id = 20
        ),
        FoodItem(
            name = "Sữa đậu nành",
            imageUrl = "https://www.bartender.edu.vn/wp-content/uploads/2020/04/sua-dau-nanh.jpg",
            category = "Sữa",
            gi = 51,
            gl = 4.029f,
            carb = 15.8f,
            chatXo = 7.9f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 ly/ngày",
            khauPhanTienTieuDuong = "≤200ml/ngày + không đường",
            khauPhanTieuDuong1 = "1 ly (12g carb)",
            khauPhanTieuDuong2 = "≤1 ly/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và phospho cao",
            id = 51
        ),
        FoodItem(
            name = "Sữa hạnh nhân",
            imageUrl = "https://cdn.tgdd.vn//News/0//cach-lam-sua-hanh-nhan-bang-may-xay-845x564-1.jpg",
            category = "Sữa",
            gi = 31,
            gl = 8.494f,
            carb = 35.2f,
            chatXo = 7.8f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "1–2 ly/ngày",
            khauPhanTienTieuDuong = "≤200ml/ngày + không đường",
            khauPhanTieuDuong1 = "1 ly (12g carb)",
            khauPhanTieuDuong2 = "≤1 ly/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và phospho cao",
            id = 2
        ),
        FoodItem(
            name = "Phô mai",
            imageUrl = "https://daylambanh.edu.vn/wp-content/uploads/2017/11/9e2da3b69f12c2eed78f14bf191f9223.jpg",
            category = "Sữa",
            gi = 54,
            gl = 13.122f,
            carb = 27.1f,
            chatXo = 2.8f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 ly/ngày",
            khauPhanTienTieuDuong = "≤200ml/ngày + không đường",
            khauPhanTieuDuong1 = "1 ly (12g carb)",
            khauPhanTieuDuong2 = "≤1 ly/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và phospho cao",
            id = 14
        ),
        FoodItem(
            name = "Sữa chua",
            imageUrl = "https://www.vinamilk.com.vn/sua-chua-vinamilk/wp-content/uploads/2015/11/2022_VNM_BQNK_SectionSP_KhongDuong.png",
            category = "Sữa",
            gi = 70,
            gl = 18.900f,
            carb = 36.3f,
            chatXo = 9.3f,
            typeGI = 3,
            typeGL = 2,
            khauPhanKhongBenh = "1–2 ly/ngày",
            khauPhanTienTieuDuong = "≤200ml/ngày + không đường",
            khauPhanTieuDuong1 = "1 ly (12g carb)",
            khauPhanTieuDuong2 = "≤1 ly/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và phospho cao",
            id = 66
        ),
        FoodItem(
            name = "Cá hồi",
            imageUrl = "https://www.nongsanantoanthanhhoa.vn/image/800/800/nq11vgcWjh8SwjgLT9emPHawLa9BTGuz3H56cQy4.png",
            category = "Hải sản",
            gi = 71,
            gl = 0.781f,
            carb = 6.8f,
            chatXo = 5.7f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "100–150g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít sốt",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và natri cao",
            id = 46
        ),
        FoodItem(
            name = "Cá thu",
            imageUrl = "https://haisan.org/upload/product/ca-thu-nhat1496143146.jpg",
            category = "Hải sản",
            gi = 75,
            gl = 4.500f,
            carb = 13.8f,
            chatXo = 7.8f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "100–150g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít sốt",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và natri cao",
            id = 31
        ),
        FoodItem(
            name = "Cá basa",
            imageUrl = "https://cdn.tgdd.vn/2021/06/CookProduct/t11-1200x676-2.jpg",
            category = "Hải sản",
            gi = 64,
            gl = 20.096f,
            carb = 38.7f,
            chatXo = 7.3f,
            typeGI = 2,
            typeGL = 3,
            khauPhanKhongBenh = "100–150g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít sốt",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và natri cao",
            id = 6
        ),
        FoodItem(
            name = "Tôm",
            imageUrl = "https://haisanloccantho.com/wp-content/uploads/2024/10/tom-cang-xanh.jpg",
            category = "Hải sản",
            gi = 36,
            gl = 5.544f,
            carb = 23.3f,
            chatXo = 7.9f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "100–150g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít sốt",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và natri cao",
            id = 49
        ),
        FoodItem(
            name = "Mực",
            imageUrl = "https://cdn.tgdd.vn/2021/03/CookProduct/20-1200x676-3.jpg",
            category = "Hải sản",
            gi = 84,
            gl = 9.240f,
            carb = 15.4f,
            chatXo = 4.4f,
            typeGI = 3,
            typeGL = 1,
            khauPhanKhongBenh = "100–150g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít sốt",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali và natri cao",
            id = 53
        ),
        FoodItem(
            name = "Thịt bò",
            imageUrl = "https://bactom.com/wp-content/uploads/2023/06/thitbo_TNJU.jpg",
            category = "Thịt",
            gi = 37,
            gl = 9.805f,
            carb = 32.9f,
            chatXo = 6.4f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "150–200g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít mỡ",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu natri cao",
            id = 7
        ),
        FoodItem(
            name = "Thịt gà",
            imageUrl = "https://fresco.vn/public/upload/product/thit-ga-co-tanh-khong-3-DBgIXBPTgf.jpg",
            category = "Thịt",
            gi = 42,
            gl = 5.208f,
            carb = 19f,
            chatXo = 6.6f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "150–200g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít mỡ",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu natri cao",
            id = 16
        ),
        FoodItem(
            name = "Thịt lợn",
            imageUrl = "https://dntt.mediacdn.vn/zoom/452_283/197608888129458176/2021/4/26/avatar1619420880501-16194208806681560789425.jpg",
            category = "Thịt",
            gi = 50,
            gl = 16.300f,
            carb = 35.3f,
            chatXo = 2.7f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "150–200g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít mỡ",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu natri cao",
            id = 40
        ),
        FoodItem(
            name = "Thịt cừu",
            imageUrl = "https://qualifoods.vn/wp-content/uploads/2023/11/thit-cuu-1.jpg",
            category = "Thịt",
            gi = 51,
            gl = 11.373f,
            carb = 32.1f,
            chatXo = 9.8f,
            typeGI = 1,
            typeGL = 2,
            khauPhanKhongBenh = "150–200g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít mỡ",
            khauPhanTieuDuong1 = "100g + không chiên",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu natri cao ",
            id = 29
        ),
        FoodItem(
            name = "Trứng gà",
            imageUrl = "https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2025/3/8/photo-1741408427825-17414084285131651116857.jpeg",
            category = "Trứng",
            gi = 33,
            gl = 1.221f,
            carb = 9.1f,
            chatXo = 5.4f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "3–4 quả/tuần",
            khauPhanTienTieuDuong = "≤3 quả/tuần + ít dầu mỡ",
            khauPhanTieuDuong1 = "1 quả/ngày",
            khauPhanTieuDuong2 = "≤3 quả/tuần",
            khauPhanBienChungThan = "Tránh nếu cholesterol cao",
            id = 17
        ),
        FoodItem(
            name = "Trứng vịt",
            imageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGi5lUbGz1CgRJCi_Y5xGJ8_UzLNdzpvVQsw&s",
            category = "Trứng",
            gi = 66,
            gl = 20.922f,
            carb = 32.5f,
            chatXo = 0.8f,
            typeGI = 2,
            typeGL = 3,
            khauPhanKhongBenh = "3–4 quả/tuần",
            khauPhanTienTieuDuong = "≤3 quả/tuần + ít dầu mỡ",
            khauPhanTieuDuong1 = "1 quả/ngày",
            khauPhanTieuDuong2 = "≤3 quả/tuần",
            khauPhanBienChungThan = "Tránh nếu cholesterol cao",
            id = 22
        ),
        FoodItem(
            name = "Trứng cút",
            imageUrl = "https://bizweb.dktcdn.net/thumb/grande/100/478/273/products/product11860.jpg?v=1720518559900",
            category = "Trứng",
            gi = 61,
            gl = 10.858f,
            carb = 18.6f,
            chatXo = 0.8f,
            typeGI = 2,
            typeGL = 2,
            khauPhanKhongBenh = "3–4 quả/tuần",
            khauPhanTienTieuDuong = "≤3 quả/tuần + ít dầu mỡ",
            khauPhanTieuDuong1 = "1 quả/ngày",
            khauPhanTieuDuong2 = "≤3 quả/tuần",
            khauPhanBienChungThan = "Tránh nếu cholesterol cao",
            id = 43
        ),
        FoodItem(
            name = "Nấm hương",
            imageUrl = "https://bizweb.dktcdn.net/100/390/808/products/1836278nam-huong-tuoi-jpeg.jpg?v=1592906200740",
            category = "Nấm",
            gi = 35,
            gl = 8.610f,
            carb = 29.4f,
            chatXo = 4.8f,
            typeGI = 1,
            typeGL = 1,
            khauPhanKhongBenh = "100–200g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít muối",
            khauPhanTieuDuong1 = "50g/bữa",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 48
        ),
        FoodItem(
            name = "Nấm kim châm",
            imageUrl = "https://bizweb.dktcdn.net/thumb/1024x1024/100/527/060/products/nam-kim-cham-han-quoc-tram-anh-food-6.jpg?v=1730346033650",
            category = "Nấm",
            gi = 58,
            gl = 15.834f,
            carb = 30.9f,
            chatXo = 3.6f,
            typeGI = 2,
            typeGL = 2,
            khauPhanKhongBenh = "100–200g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít muối",
            khauPhanTieuDuong1 = "50g/bữa",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 23
        ),
        FoodItem(
            name = "Nấm bào ngư",
            imageUrl = "https://dalatfarm.net/wp-content/uploads/2021/10/nam-bao-ngu-xam.jpg",
            category = "Nấm",
            gi = 58,
            gl = 7.366f,
            carb = 18.9f,
            chatXo = 6.2f,
            typeGI = 2,
            typeGL = 1,
            khauPhanKhongBenh = "100–200g/ngày",
            khauPhanTienTieuDuong = "≤100g/ngày + ít muối",
            khauPhanTieuDuong1 = "50g/bữa",
            khauPhanTieuDuong2 = "≤100g/ngày",
            khauPhanBienChungThan = "Tránh nếu kali cao",
            id = 36
        ),
    )
}